// Generated by CoffeeScript 1.6.2
var EventEmitter, RedisStore, redis,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

redis = require("redis");

EventEmitter = require('events').EventEmitter;

/**
 * Redis store
 * https://github.com/mranney/node_redis
*/


RedisStore = (function(_super) {
  __extends(RedisStore, _super);

  /**
   * @param options.key - basic key to store assets
  */


  function RedisStore(port, host, options) {
    var _this = this;

    if (options == null) {
      options = {};
    }
    this.assetsKey = options.key || 'redis_assets';
    this.logger = options.logger;
    if (this.logger == null) {
      this.logger = console;
    }
    this.assets = {};
    this.redis = redis.createClient(port, host, options);
    this.notify = redis.createClient(port, host, options);
    this.notify.subscribe(options.redis_assets_channel || 'redis_assets_channel');
    this.notify.on("message", function(channel, key) {
      if (key === "all") {
        return _this._update();
      } else {
        return _this.redis.hget(_this.assetsKey, key, function(err, asset) {
          if ((err != null) && (_this.logger != null)) {
            return _this.logger.error("Error hget", err);
          }
          return _this._parse(key, asset);
        });
      }
    });
    this._update();
  }

  RedisStore.prototype._update = function() {
    var _this = this;

    return this.redis.hgetall(this.assetsKey, function(err, assets) {
      var asset, key;

      if (err != null) {
        if ((err != null) && (_this.logger != null)) {
          _this.logger.error("Error hgetall", err);
        }
        _this.emit('error', err);
        return;
      }
      for (key in assets) {
        asset = assets[key];
        _this._parse(key, asset);
      }
      return _this.emit('ready');
    });
  };

  RedisStore.prototype._parse = function(key, asset) {
    var err;

    try {
      return this.assets[key] = JSON.parse(asset);
    } catch (_error) {
      err = _error;
      if (this.logger != null) {
        return this.logger.error("Error JSON.parse", err);
      }
    }
  };

  RedisStore.prototype.set = function(key, asset) {
    var _this = this;

    this.assets[key] = asset;
    return this.redis.hset(this.assetsKey, key, JSON.stringify(asset), function(err) {
      if ((err != null) && (_this.logger != null)) {
        return _this.logger.error("Error JSON.hset", err);
      }
    });
  };

  RedisStore.prototype.get = function(key) {
    return this.assets[key];
  };

  RedisStore.prototype.destroy = function(key) {
    var _this = this;

    return this.redis.hdel(this.assetsKey, key, function(err) {
      if ((err != null) && (_this.logger != null)) {
        return _this.logger.error("Error JSON.hdel", err);
      }
      return delete _this.assets[key];
    });
  };

  return RedisStore;

})(EventEmitter);

module.exports = RedisStore;
