// Generated by CoffeeScript 1.6.2
/**
 * Just a memory store
*/

var Store;

Store = (function() {
  function Store() {
    this.assets = {};
  }

  Store.prototype.set = function(key, asset) {
    return this.assets[key] = asset;
  };

  Store.prototype.get = function(key) {
    return this.assets[key];
  };

  Store.prototype.destroy = function(key) {
    return delete this.assets[key];
  };

  return Store;

})();

module.exports = Store;
